{{- if .Values.schedules.files -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "backups.fullname" . }}-files
  labels:
    {{- include "backups.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedules.files | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "backups.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: backuptools
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ['/home/backups/backup-files.sh', '/home/jka']
              env:
                - name: HOME
                  value: /home/backups
                {{- range $key, $value := .Values.env }}
                - name: "{{ tpl $key $ }}"
                  value: "{{ tpl (print $value) $ }}"
                {{- end }}
              volumeMounts:
                {{- if .Values.secrets.swift.openrc }}
                - mountPath: /home/backups/backup-openrc.sh
                  name: backup-openrc
                  subPath: backup-openrc.sh
                  readOnly: true
                {{- end }}
                {{- if .Values.secrets.gcs.sa }}
                - mountPath: /home/backups/backup-sa.json
                  name: backup-sa
                  subPath: backup-sa.json
                  readOnly: true
                {{- end }}
                {{- if .Values.volumes.data }}
                - mountPath: /home/jka
                  name: data
                {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          volumes:
            {{- if .Values.secrets.swift.openrc }}
            - name: backup-openrc
              secret:
                secretName: {{ include "backups.fullname" . }}-openrc
            {{- end }}
            {{- if .Values.secrets.gcs.sa }}
            - name: backup-sa
              secret:
                secretName: {{ include "backups.fullname" . }}-sa
            {{- end }}
            {{- with .Values.volumes.data }}
            - name: data
              {{- toYaml . | nindent 14 }}
            {{- end }}
{{- end }}
