{{- if .Values.secrets.swift.openrc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-openrc
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  backup-openrc.sh: {{ .Values.secrets.swift.openrc | quote }}
{{- end }}
---
{{- if .Values.secrets.gcs.sa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backups.fullname" . }}-sa
  labels:
    {{- include "backups.labels" . | nindent 4 }}
type: Opaque
stringData:
  backup-sa.json: {{ .Values.secrets.gcs.sa | b64dec | quote }}
{{- end }}
