{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailserver.fullname" . }}-env
  labels:
    {{- include "mailserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.dkim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailserver.fullname" . }}-dkim-key
  labels:
    {{- include "mailserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  private.key: |
    {{- .Values.dkim.config.privateKey | nindent 4 }}
{{- end }}
