apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "jobs.fullname" . }}-piwik-archive
  labels:
    {{- include "jobs.labels" . | nindent 4 }}
spec:
  schedule: {{ index .Values.schedules "piwik-archive" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "jobs.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: php
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ['/usr/bin/php', '/srv/www/apps/piwik/console', 'core:archive']
              volumeMounts:
                {{- if .Values.volumes.apps }}
                - mountPath: /srv/www/apps
                  name: apps
                {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          volumes:
            {{- with .Values.volumes.apps }}
            - name: apps
              {{- toYaml . | nindent 14 }}
            {{- end }}
