apiVersion: v1
kind: Service
metadata:
  name: {{ include "jka.fullname" . }}
  labels:
    {{- include "jka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jka-server
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: jka
      protocol: UDP
      name: jka
  {{- if .Values.service.alternatePort }}
    - port: {{ .Values.service.alternatePort }}
      nodePort: {{ .Values.service.alternateNodePort }}
      targetPort: jka
      protocol: UDP
      name: altjka
  {{- end }}
  externalTrafficPolicy: Local
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
