apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logstash.fullname" . }}-secret
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret }}
  {{- toYaml .Values.secret | nindent 2 }}
  {{- end }}
