{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logstash.fullname" . }}-env
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logstash.fullname" . }}-secret
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret | nindent 2 }}
{{- end }}
