apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ftp.fullname" . }}-config
  labels:
    {{- include "ftp.labels" . | nindent 4 }}
stringData:
  {{- if .Values.ftp.home }}
  FTP_HOME: "{{ .Values.ftp.home }}"
  {{- end }}
  {{- if .Values.ftp.uid }}
  FTP_UID: "{{ .Values.ftp.uid }}"
  {{- end }}
  {{- if .Values.ftp.gid }}
  FTP_GID: "{{ .Values.ftp.gid }}"
  {{- end }}
  {{- if .Values.ftp.users }}
  FTP_USERS: "{{ .Values.ftp.users }}"
  {{- end }}
  {{- if .Values.ftp.passiveAddress }}
  VSFTPD_pasv_address: "{{ .Values.ftp.passiveAddress }}"
  {{- end }}
  VSFTPD_pasv_min_port: "{{ .Values.ftp.passivePortMin }}"
  VSFTPD_pasv_max_port: "{{ .Values.ftp.passivePortMax }}"
  {{- if .Values.cert.enabled }}
  VSFTPD_rsa_cert_file: "/etc/vsftpd/ssl/tls.crt"
  VSFTPD_rsa_private_key_file: "/etc/vsftpd/ssl/tls.key"
  VSFTPD_ssl_enable: "YES"
  {{- end }}
  {{- range $key, $value := .Values.ftp.options }}
  VSFTPD_{{ tpl $key $ }}: "{{ tpl (print $value) $ }}"
  {{- end }}
