apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftp.fullname" . }}
  labels:
    {{- include "ftp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ftp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: ftp
      protocol: TCP
      name: ftp
  {{- range untilStep (.Values.service.passivePortMin | int) (.Values.service.passivePortMax | int) 1 }}
    - port: {{ . }}
      nodePort: {{ add . (sub $.Values.service.passiveNodePortMin $.Values.service.passivePortMin) }}
      targetPort: {{ add . (sub $.Values.ftp.passivePortMin $.Values.service.passivePortMin) }}
      protocol: TCP
      name: pasv{{ . }}
  {{- end }}
  externalTrafficPolicy: Local
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
