apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activemq.fullname" . }}-admin-secret
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.admin.username }}
  password: {{ .Values.secrets.admin.password }}
