fullnameOverride: logstash

env:
  ELASTICSEARCH_CACERT: /usr/share/logstash/secret/elasticsearch-ca.crt
  ELASTICSEARCH_HOSTS: https://infra-es-http.infra.svc:9200
  ELASTICSEARCH_USERNAME: elastic
  LOGSTASH_PLUGINS: logstash-output-stomp
  LS_JAVA_OPTS: -Xms512m -Xmx512m
  XPACK_MONITORING_ENABLED: "false"

pipeline:
  activemq.conf: |
    output {
      # JKA Server Log
      if "jka-games" in [tags] {
        stomp {
          host => "activemq.domain-jediholo-net.svc"
          port => 61613
          destination => "/topic/jka.%{modname}.%{servername}.games.log"
          headers => [ "amq-msg-type", "text", "type", "%{type}" ]
        }
      }
    }

volumes:
  - name: data
    hostPath:
      path: /home/jka/.logstash/data
      type: DirectoryOrCreate
  - name: jka
    hostPath:
      path: /home/jka
      type: DirectoryOrCreate
volumeMounts:
  - mountPath: /usr/share/logstash/data
    name: data
  - mountPath: /home/jka
    name: jka
    readOnly: true
