apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}-root-secret
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.root.username }}
  password: {{ .Values.secrets.root.password }}
