apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}-root-secret
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.root.username }}
  password: {{ .Values.secrets.root.password }}
---
{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}-env
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
