apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldap.fullname" . }}
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.alternatePort }}
      targetPort: tcp
      protocol: TCP
      name: alttcp
  selector:
    {{- include "ldap.selectorLabels" . | nindent 4 }}
