apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php.fullname" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "php.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "php.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "php.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 9000
              protocol: TCP
          env:
            - name: HOME
              value: /srv/www
            {{- range $key, $value := .Values.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl (print $value) $ }}"
            {{- end }}
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            tcpSocket:
              port: tcp
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            exec:
              command: ['/bin/sh', '-c', 'REQUEST_METHOD=GET SCRIPT_NAME=/php-fpm-ping SCRIPT_FILENAME=/php-fpm-ping cgi-fcgi -bind -connect 127.0.0.1:9000 | grep pong']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.volumes.sessions }}
            - mountPath: /var/lib/php7
              name: sessions
            {{- end }}
            {{- if .Values.volumes.logs }}
            - mountPath: /var/log/php-fpm
              name: logs
            {{- end }}
            {{- if .Values.volumes.apps }}
            - mountPath: /srv/www/apps
              name: apps
            {{- end }}
            {{- if .Values.volumes.subdomains }}
            - mountPath: /srv/www/sd
              name: subdomains
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.volumes.sessions }}
        - name: sessions
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.logs }}
        - name: logs
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.apps }}
        - name: apps
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumes.subdomains }}
        - name: subdomains
          {{- toYaml . | nindent 10 }}
        {{- end }}
