{{- if .Values.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "php.fullname" . }}-env
  labels:
    {{- include "php.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
  {{- end }}
{{- end }}
