apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpbb.fullname" . }}-config
  labels:
    {{- include "phpbb.labels" . | nindent 4 }}
data:
  mod_remoteip.conf: |
    LoadModule remoteip_module modules/mod_remoteip.so
    RemoteIPHeader X-Forwarded-For
    RemoteIPInternalProxy 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
