{{- if .Values.schedules.skinpack -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backups.fullname" . }}-skinpack
  labels:
    {{- include "backups.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedules.skinpack | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "backups.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: backuptools
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: ['/home/backups/backup-archive.sh', 'JEDI_Skins', '/srv/www/sd/files/htdocs/repos/jedi-skins/assets', '*.pk3']
              env:
                - name: HOME
                  value: /home/backups
                - name: BACKUP_DIR
                  value: /srv/www/sd/files/htdocs
                - name: BACKUP_SUBDIR
                  value: downloads
              volumeMounts:
                {{- if .Values.volumes.domain }}
                - mountPath: /srv/www
                  name: domain
                {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          volumes:
            {{- with .Values.volumes.domain }}
            - name: domain
              {{- toYaml . | nindent 14 }}
            {{- end }}
{{- end }}
